service: sls-project

provider:
    name: aws
    runtime: nodejs16.x
    region: sa-east-1

functions:     

plugins:
    - serverless-offline
    - serverless-localstack
    - serverless-plugin-typescript
